### ISSUE TITLE
Utilizar herencia para las clases de productos

### ISSUE THREAD

**Issue by JuanseGimenez** [IsnardMatias/Kwik-E-Mart#1]

**Comment by tebayoso** [comment]
No implementes una clase para cada producto, el comportamiento en el sistema de todos los productos es el mismo, si lo que quieres es cambiar los atributos de cada producto, como el precio o el nombre, deberias guardar la información en una capa de persistencia, como una base de datos, o en el mejor escenario, un YML/CSV que se cargue diariamente.
